import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {formatSlideX} from '../dist/format.js';
import {parseSlideX} from '../dist/ir.js';
import {parsePages} from '../dist/export/pages.js';
import {exportDeck} from '../dist/export/export.js';

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'slidex-dsl-tools-')),file=path.join(dir,'deck.slx');
const rich='<text id="t" x="10" y="10" w="200" h="100"><p>Hello  <strong>world</strong> &amp; friends</p></text>';
const code='<code id="c" x="10" y="120" w="200" h="100">\n  if (a<b) {\n    run("x > y");\n  }\n</code>';
const xml=`<?xml version="1.0"?><deck version="1" width="320" height="240"><!-- kept --><slide id="first">${rich}${code}</slide><slide id="second"><text id="t2" x="20" y="20" w="200" h="100">Second</text></slide><slide id="third"/></deck>`;
const formatted=formatSlideX(xml);
assert.ok(formatted.includes(rich)&&formatted.includes(code)&&formatted.includes('<!-- kept -->'));
assert.equal(formatSlideX(formatted),formatted);
const stripLocations=x=>JSON.parse(JSON.stringify(x,(key,value)=>key==='line'||key==='col'?undefined:value));
assert.deepEqual(stripLocations(parseSlideX(formatted).deck),stripLocations(parseSlideX(xml).deck));
assert.throws(()=>formatSlideX('<deck><slide></deck>'));
const cdata='<deck version="1"><slide><!-- c --><text><![CDATA[<text> literal </text>]]></text><code><![CDATA[if (x<y) a();]]></code></slide></deck>';
assert.ok(formatSlideX(cdata).includes('<![CDATA[<text> literal </text>]]>'));
assert.deepEqual(stripLocations(parseSlideX(cdata).deck),stripLocations(parseSlideX(formatSlideX(cdata)).deck));
assert.deepEqual(parsePages('3,1-2,2',3),[0,1,2]);
for(const bad of ['', '0','4','2-1','1,','-1','1.5'])assert.throws(()=>parsePages(bad,3));
fs.writeFileSync(file,xml);
const cli=(...args)=>spawnSync(process.execPath,['dist/cli.js',...args],{encoding:'utf8'});
assert.equal(cli('format',file,'--check').status,1);
assert.equal(cli('format',file).stdout,formatted);assert.equal(fs.readFileSync(file,'utf8'),xml);
assert.equal(cli('format',file,'--write').status,0);assert.equal(cli('format',file,'--check').status,0);
assert.equal(cli('export',file,'--pages').status,1);
const validated=cli('validate',file,'--json');assert.equal(validated.status,0);assert.equal(JSON.parse(validated.stdout).ok,true);
const result=await exportDeck(file,{format:'png',pages:'2-3',scale:1,manifest:true});
assert.deepEqual(result.files.map(f=>path.basename(f)),['deck-02.png','deck-03.png','deck-images.json','deck.png.report.json']);
assert.ok(!fs.existsSync(path.join(dir,'out','deck-01.png')));
const manifest=JSON.parse(fs.readFileSync(result.files[2],'utf8'));assert.deepEqual(manifest.pages.map(p=>[p.page,p.id]),[[2,'second'],[3,'third']]);
for(const file of result.files.slice(0,2)){const png=fs.readFileSync(file);assert.equal(png.readUInt32BE(16),320);assert.equal(png.readUInt32BE(20),240);}
await assert.rejects(exportDeck(file,{pages:'0'}));await assert.rejects(exportDeck(file,{format:'pdf',pages:'1'}));await assert.rejects(exportDeck(file,{scale:0}));
fs.writeFileSync(file,'<deck><slide></deck>');const invalid=cli('validate',file,'--json');assert.equal(invalid.status,1);assert.ok(JSON.parse(invalid.stdout).errors.length);
console.log('PASS DSL formatting, diagnostics CLI, page ranges and real PNG/manifest export:',dir);
