import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {loadProject,saveProject} from '../dist/project.js';
import {serializeDeck} from '../dist/serializer.js';
import {parseSlideX} from '../dist/ir.js';
import {languageInfo} from '../dist/language.js';
import {startServer} from '../dist/server.js';
import {exportDeck} from '../dist/export/export.js';
import {historyStore} from '../dist/revisions.js';
import {formatSlideX} from '../dist/format.js';
import {withBrowser} from '../dist/export/capture.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'slidex-project-')),file=path.join(dir,'deck.slx');
fs.mkdirSync(path.join(dir,'pages'));fs.mkdirSync(path.join(dir,'pages/media'));
fs.writeFileSync(path.join(dir,'pages/media/pic.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="red"/></svg>');
const fragment='<slide id="one"><image id="image" x="0" y="0" w="80" h="80" src="media/pic.svg"/><text id="text" x="100" y="20" w="200" h="60"><b>Content &amp; symbols</b></text><animation target="text" effect="pulse"/></slide>';
fs.writeFileSync(path.join(dir,'pages/one.slx'),fragment);
fs.writeFileSync(path.join(dir,'pages/all.slx'),'<slides><include src="one.slx"/><slide id="two"><text id="text" x="0" y="0" w="100" h="40" href="slide:one">Second</text></slide></slides>');
fs.writeFileSync(file,'<deck version="1" width="320" height="240"><include src="pages/all.slx"/></deck>');
let project=loadProject(file);assert.deepEqual(project.errors,[]);assert.equal(project.deck.slides.length,2);assert.equal(project.deck.slides[0].elements[0].src,'pages/media/pic.svg');
project.deck.slides[0].elements[1].content='Edited';
let saved=saveProject(project,serializeDeck(project.deck));assert.deepEqual(saved.errors,[]);assert.equal(saved.deck.slides[0].elements[1].content,'Edited');assert.equal(fs.readFileSync(path.join(dir,'pages/one.slx'),'utf8'),fragment);assert.match(fs.readFileSync(file,'utf8'),/<include/);assert.equal(saved.deck.slides[0].elements[0].src,'pages/media/pic.svg');
assert.throws(()=>saveProject(saved,serializeDeck(saved.deck).replace('pages/media/pic.svg','../outside.svg')),/媒体路径/);
const old=fs.readFileSync(file,'utf8'),oldVersion=saved.version;
const dependency=saved.files.find(f=>f.path!==file).path;fs.appendFileSync(dependency,'\n<!-- external -->');
assert.throws(()=>saveProject(saved,serializeDeck(saved.deck)),/外部修改/);assert.equal(fs.readFileSync(file,'utf8'),old);
saved=loadProject(file);assert.notEqual(saved.version,oldVersion);
const rename=fs.renameSync;try{fs.renameSync=(from,to)=>{if(to===file)throw Error('simulated rename failure');return rename(from,to);};saved.deck.slides[0].notes='staged';assert.throws(()=>saveProject(saved,serializeDeck(saved.deck)),/simulated/);}finally{fs.renameSync=rename;}
assert.equal(fs.readFileSync(file,'utf8'),old);assert.deepEqual(loadProject(file).errors,[]);
assert.match(formatSlideX(old),/<include/);
const invalid=path.join(dir,'invalid.slx');
fs.writeFileSync(invalid,'<deck><include src="missing.slx"/></deck>');assert.ok(loadProject(invalid).errors.some(e=>e.code==='E_INCLUDE_MISSING'&&e.file===invalid));
fs.writeFileSync(invalid,'<deck><include src="../outside.slx"/></deck>');assert.ok(loadProject(invalid).errors.length);
fs.writeFileSync(invalid,'<deck><include src="pages/cycle.slx"/></deck>');fs.writeFileSync(path.join(dir,'pages/cycle.slx'),'<slides><include src="cycle.slx"/></slides>');assert.ok(loadProject(invalid).errors.some(e=>e.code==='E_INCLUDE_CYCLE'));
fs.writeFileSync(invalid,'<deck><include src="pages/bad.slx"/></deck>');fs.writeFileSync(path.join(dir,'pages/bad.slx'),'<slide id="bad">\n<shape id="x" name="oops" x="0" y="0" w="20" h="20"/>\n</slide>');assert.ok(loadProject(invalid).errors.some(e=>e.code==='E_SHAPE_NAME'&&e.file.endsWith('bad.slx')&&e.line===2));
const text='<deck><slide id="p"><shape id="s" name="rect" x="0" y="0" w="10" h="10"/><animation target="s" effect="fade-in"/></slide></deck>';
assert.ok(languageInfo(text,text.indexOf('rect')+2).completions.some(c=>c.insertText==='rect'&&c.to===text.indexOf('rect')+4));assert.equal(languageInfo(text,text.indexOf('target="s"')+9).definition.id,'s');
const preferencesFile=path.join(dir,'settings/preferences.json');let server=await startServer(file,{port:0,preferencesFile});
try{
  let base=`http://127.0.0.1:${server.port}`;
  const doc=await (await fetch(base+'/api/deck')).json();assert.equal(doc.multiFile,true);
  const post=async(url,body)=>fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  assert.equal((await post('/api/save',{xml:doc.xml,expectedVersion:'stale'})).status,409);
  const draft=doc.xml.replace('Edited','Recovered');await post('/api/draft',{path:file,xml:draft});
  server.close();server=await startServer(file,{port:0,preferencesFile});base=`http://127.0.0.1:${server.port}`;
  const history=await (await fetch(base+'/api/revisions')).json();assert.ok(history.revisions.some(r=>r.draft&&r.xml===draft));
  const good=await (await post('/api/save',{xml:doc.xml,expectedVersion:doc.version,expectedPath:file})).json();assert.equal(good.ok,true,JSON.stringify(good));
  await withBrowser(async browser=>{
    const page=await browser.newPage();await page.setViewport({width:1440,height:1000});await page.goto(base);await page.waitForSelector('#canvasHost [data-id="text"]');
    await page.click('#canvasHost [data-id="text"]',{clickCount:2});await page.waitForSelector('.ProseMirror');await page.click('.ProseMirror');await page.keyboard.type(' browser');await page.click('.canvas-caption');assert.equal(await page.evaluate(()=>window.__slxSave()),true);
    await page.reload();await page.waitForSelector('#canvasHost [data-id="text"]');assert.match(await page.evaluate(()=>window.__slxGetXml()),/browser/);
  });
  const reloaded=loadProject(file);assert.equal(reloaded.deck.slides[0].animations[0].target,'text');assert.match(fs.readFileSync(file,'utf8'),/<include/);assert.equal(fs.readFileSync(path.join(dir,'pages/one.slx'),'utf8'),fragment);
  const media=await fetch(base+'/f/pages/media/pic.svg');const etag=media.headers.get('etag');await media.text();assert.equal((await fetch(base+'/f/pages/media/pic.svg',{headers:{'If-None-Match':etag}})).status,304);
  const result=await exportDeck(file,{format:'png',pages:'2',scale:1,manifest:true});
  const manifest=JSON.parse(fs.readFileSync(result.files.find(f=>f.endsWith('-images.json')),'utf8'));assert.equal(manifest.pages[0].id,'two');assert.equal(manifest.pages[0].width,320);assert.ok(fs.existsSync(manifest.pages[0].path));assert.equal(manifest.failure,null);
  await assert.rejects(exportDeck(invalid,{format:'png',manifest:true}),error=>error.details?.failure.code==='DOCUMENT_INVALID'&&error.details.diagnostics.some(e=>e.file.endsWith('bad.slx')));
  await assert.rejects(exportDeck(file,{format:'png',pages:'999',manifest:true}),error=>error.details?.status==='failed'&&!!error.details.failure.message);
  const historyDir=path.join(dir,'corrupt-history'),store=historyStore(historyDir);store.record(file,doc.xml);
  const historyFile=path.join(historyDir,fs.readdirSync(historyDir)[0]);fs.writeFileSync(historyFile,'{corrupt');assert.throws(()=>store.record(file,draft));assert.equal(fs.readFileSync(historyFile,'utf8'),'{corrupt');
}finally{server.close();}
console.log('PASS project includes/media/source diagnostics, atomic COW save/conflicts, language service, durable recovery and manifest:',dir);
